# Generated by Django 2.1 on 2019-06-17 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='movies',
            new_name='movie',
        ),
    ]
